### ISSUE TITLE
This is not realy an issue but...

### ISSUE THREAD

**Issue by antenando** [mreq/sublime-better-close-window#1]
...didn't [Build 3061](http://www.sublimetext.com/3dev) solved that?
- Tweaked window closing behavior when pressing ctrl+w / cmd+w

**Comment by mreq** [comment]
Nope, not really. See the annoyance I posted in [Package Control pull-request](https://github.com/wbond/package_control_channel/pull/3192#issuecomment-42340240). I'll close this, feel free to reopen if you find the plugin redundant.

I updated the README so that the plugin's effect is more transparent.
